name: RiskyContrib
channels:
  - conda-forge
dependencies:
  - python=3.7
  - matplotlib-base=3.3.3
  - numpy=1.18
  - ipython=7.11.1
  - scipy=1.7.0
  - seaborn=0.11.1
  - pandas=1.3.0
  - pip:
    - git+git://github.com/econ-ark/HARK/tree/83f1b8b53d91129a52c07199912ae5e371b75c60
