name: RiskyContrib
channels:
  - conda-forge
dependencies:
  - python=3.7
  - matplotlib-base=3.3.3
  - numpy=1.18
  - ipython=7.11.1
  - scipy
  - seaborn
  - pandas
  - jupyter_contrib_nbextensions
